version: '3.8'

services: # 

  halloween-horror-night: # unique name for container
    image: halloween-horror-night # 
    container_name: halloween-horror-night
    build:
      context: .
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - '.:/app'
      - node_modules:/app/node_modules
      - build:/.next
    env_file:
      - .env

volumes:
  node_modules:
  build: